### ISSUE TITLE
Imported annotations get deleted when scrolling through images

### ISSUE THREAD

**Issue by mgarbade** [jsbroks/coco-annotator#377]
Currently I can import my annotations but once I walk through the images (forward using "n" and backward using "p") annotations disappear and apparantly get deleted (which is a serious problem). I tried to load different commits / docker-image versions (stable, v0.10, developer yml) but the problem keeps on coming.

Weirdly I also cannot go around this error by going to an older commit. Seems like whatever images docker is pulling to build the dev.yml already contains the bug

**Comment by mgarbade** [comment]
```
annotator_webclient | [2020-05-21 15:04:52 +0000] [10] [DEBUG] POST /api/annotator/data
annotator_webclient | [2020-05-21 15:04:52 +0000] [10] [DEBUG] GET /api/image/2476
annotator_webclient | [2020-05-21 15:04:52 +0000] [10] [DEBUG] GET /api/annotator/data/2476
annotator_webclient | [2020-05-21 15:04:53 +0000] [10] [DEBUG] DELETE /api/annotation/539
annotator_webclient | [2020-05-21 15:04:53 +0000] [10] [DEBUG] POST /api/annotator/data
annotator_webclient | [2020-05-21 15:04:53 +0000] [10] [DEBUG] GET /api/image/2106
annotator_webclient | [2020-05-21 15:04:53 +0000] [10] [DEBUG] GET /api/annotator/data/2106
annotator_webclient | [2020-05-21 15:04:54 +0000] [10] [DEBUG] DELETE /api/annotation/587
annotator_webclient | [2020-05-21 15:04:54 +0000] [10] [DEBUG] POST /api/annotator/data
annotator_webclient | [2020-05-21 15:04:54 +0000] [10] [DEBUG] GET /api/image/2112
annotator_webclient | [2020-05-21 15:04:54 +0000] [10] [DEBUG] GET /api/annotator/data/2112
annotator_webclient | [2020-05-21 15:04:57 +0000] [10] [DEBUG] DELETE /api/annotation/550
annotator_webclient | [2020-05-21 15:04:57 +0000] [10] [DEBUG] POST /api/annotator/data
annotator_webclient | [2020-05-21 15:04:57 +0000] [10] [DEBUG] GET /api/annotator/data/2106
annotator_webclient | [2020-05-21 15:04:57 +0000] [10] [DEBUG] POST /api/annotator/data
annotator_webclient | [2020-05-21 15:04:57 +0000] [10] [DEBUG] GET /api/annotator/data/2476
annotator_webclient | [2020-05-21 15:04:58 +0000] [10] [DEBUG] POST /api/annotator/data
annotator_webclient | [2020-05-21 15:04:58 +0000] [10] [DEBUG] GET /api/annotator/data/2273
```

this is the console output when scrolling through images using "n" and "p" shortcut or by clicking on the "next image" arrows. Note that "DELETE" is called, for whatever reason. 
I'm using the latest commit of the coco-annotator, but I also tried older ones as well as `0.10`. 

This is kind of a serious problem so any help would be appreciated. 

The weird thing is, that going back to an older version of the code seems not to help... no idea how that can be. Maybe some other services (mongodb or rabbitmq) are causing the issue :thinking:

**Comment by mgarbade** [comment]
Bug does not exist in the newest version when using the dev.yml build

**Comment by jsbroks** [comment]
Exports should be working in latest.

**Comment by mgarbade** [comment]
Thanks a lot for the fix!
- Exports are working in `docker-compose.dev.yml` version

FYI (not urgent):
- Exports issue persists in production version
